# Generated by Django 3.2.5 on 2021-07-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sushi',
            options={'verbose_name_plural': 'Sushi'},
        ),
        migrations.AddField(
            model_name='sushi',
            name='category',
            field=models.CharField(default='first', max_length=100),
        ),
        migrations.AlterField(
            model_name='sushi',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
