# Generated by Django 3.2.5 on 2021-07-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi', '0002_auto_20210708_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='sushi',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
