# Generated by Django 3.2.5 on 2021-07-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushi', '0003_auto_20210708_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='sushi',
            name='image',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='sushi',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
